quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

mp.jwt.verify.publickey.location=classpath:publicKey.pem
mp.jwt.verify.issuer=https://coolstore.vn

#quarkus.http.auth.permission.public.paths=/api/products,/api/products/categories,/api/auth/dang-nhap
#quarkus.http.auth.permission.public.policy=permit
#
#quarkus.http.auth.permission.jwt.paths=/api/orders/*,/api/auth/*,/api/products POST,/api/products PUT,/api/products DELETE
#quarkus.http.auth.permission.jwt.policy=authenticated

# PUBLIC
quarkus.http.auth.permission.public.paths=/api/products,/api/products/*,/api/auth/dang-nhap
quarkus.http.auth.permission.public.policy=permit

# JWT USER
quarkus.http.auth.permission.jwt.paths=/api/orders/*,/api/auth/*
quarkus.http.auth.permission.jwt.policy=authenticated

# ADMIN
quarkus.http.auth.permission.admin.paths=/api/products/*
quarkus.http.auth.permission.admin.methods=POST,PUT,DELETE
quarkus.http.auth.permission.admin.policy=authenticated

quarkus.http.auth.proactive=false

#http://localhost:8080/api/auth/dang-nhap